{% set version = "1.3.2" %}
package:
  name: harfbuzz
  version: {{ version }}

source:
  fn: harfbuzz-{{ version }}.tar.bz2
  url: http://www.freedesktop.org/software/harfbuzz/release/harfbuzz-{{ version }}.tar.bz2
  sha256: 8543a6372f08c5987c632dfaa86210c7edb3f43fbacd96095c609bc3539ce027

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: True  # [win]

requirements:
  build:
    - perl
    - pkg-config
    - automake
    - libtool
    - cairo 1.12.*
    - glib 2.*
    - freetype 2.6.*
    - icu 56.*
  run:
    - cairo 1.12.*
    - glib 2.*
    - freetype 2.6.*
    - icu 56.*

test:
  commands:
    # Libraries.
    {% set libs = [
      "libharfbuzz-icu",
      "libharfbuzz"
      ] %}
    {% for lib in libs %}
    - test -f $PREFIX/lib/{{ lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/{{ lib }}.so  # [linux]
    {% endfor %}
    # CLI tests.
    - hb-view --version  # [linux]
    #- conda inspect linkages -p $PREFIX harfbuzz  # [not win]
    #- conda inspect objects -p $PREFIX harfbuzz  # [osx]

about:
  home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
  license: MIT
  license_file: COPYING
  summary: 'An OpenType text shaping engine.'
  description: |
    HarfBuzz is a text shaping library. New Harbuzz targets various font
    technologies while Old HarfBuzz targets only OpenType fonts.
  doc_url: https://www.freedesktop.org/wiki/Software/HarfBuzz/
  dev_url: https://github.com/behdad/harfbuzz

extra:
  recipe-maintainers:
    - ocefpaf
