{% set name = "harfbuzz" %}
{% set version = "6.0.0" %}
{% set sha256 = "6d753948587db3c7c3ba8cc4f8e6bf83f5c448d2591a9f7ec306467f3a4fe4fa" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/harfbuzz/harfbuzz/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - gir-windows.patch  # [win]
    # We don't ship static libraries, and having the Requires.Private
    # Makes downstream packages depend on the development libraries of
    # harfbuzz
    # https://github.com/conda-forge/conda-forge.github.io/issues/1880
    - remove_requires_private.patch

build:
  number: 1
  run_exports:
    # pretty excellent forward compatibility
    # https://abi-laboratory.pro/index.php?view=timeline&l=harfbuzz
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - gobject-introspection
    - meson
    - ninja
    - pkg-config
    - pthread-stubs
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cairo      # [build_platform != target_platform]
    - glib       # [build_platform != target_platform]
    - freetype   # [build_platform != target_platform]
    - icu        # [build_platform != target_platform]
    - graphite2  # [build_platform != target_platform]
  host:
    - cairo
    - glib
    - freetype
    - icu
    - graphite2
  run:
    - cairo
    - freetype
    - icu
    - graphite2

test:
  requires:
    - pygobject
  commands:
    # Just inspect for now
    - echo harfbuzz.pc                                  # [unix]
    - cat ${PREFIX}/lib/pkgconfig/harfbuzz.pc           # [unix]
    - echo harfbuzz-gobject.pc                          # [unix]
    - cat ${PREFIX}/lib/pkgconfig/harfbuzz-gobject.pc   # [unix]
    - echo harfbuzz-icu.pc                              # [unix]
    - cat ${PREFIX}/lib/pkgconfig/harfbuzz-icu.pc       # [unix]
    - echo harfbuzz-subset.pc                           # [unix]
    - cat ${PREFIX}/lib/pkgconfig/harfbuzz-subset.pc    # [unix]
    # Libraries/headers.
    {% set libs = [
        "harfbuzz-gobject",
        "harfbuzz-icu",
        "harfbuzz"
        ] %}
    {% for lib in libs %}
    - test -f $PREFIX/lib/lib{{ lib }}${SHLIB_EXT}    # [unix]
    - if not exist %PREFIX%\Library\bin\{{ lib }}.dll exit 1       # [win]
    {% endfor %}
    - test -f $PREFIX/include/harfbuzz/hb-ft.h    # [not win]
    - if not exist %PREFIX%\Library\include\harfbuzz\hb-ft.h exit 1         # [win]
    - test -f $PREFIX/lib/girepository-1.0/HarfBuzz-0.0.typelib    # [unix]
    - if not exist %PREFIX%\Library\lib\girepository-1.0\HarfBuzz-0.0.typelib exit 1         # [win]
    # CLI tests.
    - hb-view --version  # [linux]

about:
  home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
  license: MIT
  license_file: COPYING
  summary: An OpenType text shaping engine.
  description: |
    HarfBuzz is a text shaping library. New Harbuzz targets various font
    technologies while Old HarfBuzz targets only OpenType fonts.
  doc_url: https://www.freedesktop.org/wiki/Software/HarfBuzz/
  dev_url: https://github.com/behdad/harfbuzz

extra:
  recipe-maintainers:
    - ocefpaf
    - pkgw
    - tschoonj
