{% set name = "harfbuzz" %}
{% set version = "2.7.2" %}
{% set sha256 = "8ec112ee108642477478b75fc7906422abed404d7530e47ba0a4875f553f1b59" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/harfbuzz/harfbuzz/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  run_exports:
    # pretty excellent forward compatibility
    # https://abi-laboratory.pro/index.php?view=timeline&l=harfbuzz
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - gobject-introspection  # [not win]
    - meson
    - ninja
    - pkg-config
    - pthread-stubs
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cairo
    - glib
    - freetype
    - icu
    - graphite2
  run:
    - cairo
    - freetype
    - icu
    - graphite2

test:
  commands:
    # Libraries/headers.
    {% set libs = [
        "libharfbuzz-icu",
        "libharfbuzz"
        ] %}
    {% for lib in libs %}
    - test -f $PREFIX/lib/{{ lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/{{ lib }}.so  # [linux]
    {% endfor %}
    - test -f $PREFIX/include/harfbuzz/hb-ft.h  # [not win]
    # CLI tests.
    - hb-view --version  # [linux]

about:
  home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
  license: MIT
  license_file: COPYING
  summary: 'An OpenType text shaping engine.'
  description: |
    HarfBuzz is a text shaping library. New Harbuzz targets various font
    technologies while Old HarfBuzz targets only OpenType fonts.
  doc_url: https://www.freedesktop.org/wiki/Software/HarfBuzz/
  dev_url: https://github.com/behdad/harfbuzz

extra:
  recipe-maintainers:
    - ocefpaf
    - pkgw
    - tschoonj
