appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
azure: {force: false}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: lJ58+BmnsmIsgL9xzT38o8lmkd/4YLCFxrDDr0xzs4Qkzbe4IL8vCK7fLwNTMrbx2m2ThH7xcJRaPhqbhotG4Gg+my0Qot0xipSmp06rvpVqFlOXE/lo6dPG1K9dB2MrvjDjSE6diME7sUfDHKG7CahtvBi9rO+AAXdRs5t6prvW+GIzhMo6R58vsoRHSWMQLucFlsUOL68uqqi6TdX8vFjf3IQ1ASuY62YFYmFyMUKeA/4PkRLscYGBwO6pdNSpdjHf18/e0wUoWvVvRLssS/xbVEdu2iaQ8GU7HPBkyrvylYeozKuM5nes8B5vxuChD7Yu8KW2FV2D8chegS5qQIz+ga6HKItU9I6uheRSSu1EmZn/+lxjOXEbyHM+JlSJb1P5qMebAq42U0TGLi2inG9MicWgtZ/bcDC/QKAibl9O4kZPM5M3EXLPLaJ1cP81C1N4IqQOCwN+k1R9MEUWbqOkwINoqG4YXvFPSkaywqm28AsRDOeLldoP2USCX8GgSd/2VA3IQ0Z86U4zSQeEUbOdFrIL2SNouZWt85oa0+34IfoBJhO4ZpC0vSTU5YmzjSuvorOLldR9uxM4eQZTL3GYfMTq4BLxuON2W3mCYv8zZB71UQISenLBvf72i6rY/VoNUc0WdCI9V1ybDmhNBcvwVnPMGmZZhKvMdci7wYo=}
